let orgTotal = []

let LLYCParrUno = "LLYC es una consultora global de comunicación que aporta visión estratégica, creatividad y tecnología al servicio de tu comunicación, influencia y negocio."

let LLYCParrDos = "LLYC es una firma que siempre tiene al cliente en el centro del negocio, volcada en el crecimiento para desarrollar el talento y ofrecer soluciones integrales en las que la tecnología, innovación y creatividad actúan como palancas de su propuesta de valor."

let LLYCParrTres = "LLYC cuenta con 16 oficinas y está presente en 13 países: Argentina, Brasil, Colombia, Chile, Ecuador, España, Estados Unidos, México, Panamá, Perú, Portugal y República Dominicana. También presta servicios a través de compañías afiliadas en el resto de los mercados de América Latina y participa en diversas alianzas, entre otras, Finsbury Glover Hering."

// let FaraUno
// let FaraDos
// let FaraTres

// STOCK BASES
orgTotal.push(
    {id:1, nombre: "Llorente y Cuenca", 
                img: "./img/Logos/LogoLLYC.jfif",
                Phone: "", 
                Mail:"", 
                WebSite:"https://www.llorenteycuenca.com" , 
                linkedIn: "https://www.linkedin.com/company/llyc/", 
                descUno: LLYCParrUno, descDos: LLYCParrDos, descTres: LLYCParrTres},
    {id:2, nombre: "Fara y Asociados", 
                img: "./img/Logos/LogoFara.jpg",
                Phone: "", 
                Mail:"", 
                WebSite:"http://www.carlosfarayasoc.com.ar" , 
                linkedIn: "https://www.linkedin.com/in/carlosfara/", 
                descripcion: "Breve Descripcion del Producto para mostrar al hacer click"},
    {id:3, nombre: "Jeffrey Group", 
                img: "./img/Logos/LogoJeffrey.png",
                Phone: "", 
                Mail:"", 
                WebSite:"https://www.jeffreygroup.com/ar/" , 
                linkedIn: "https://www.linkedin.com/company/jeffreygroup/", 
                descripcion: "Breve Descripcion del Producto para mostrar al hacer click"},
    {id:4, nombre: "Gerencia de Planificación del GCBA", 
                img: "./img/Logos/LogoGCBA.png",
                Phone: "", 
                Mail:"", 
                WebSite:"https://www.buenosaires.gob.ar/jefaturadegabinete/planificacionycoordinaciondegestion/institucional-secretaria-de-planificacion-evaluacion-y-coordinacion-de-gestion" , 
                linkedIn: "https://www.linkedin.com/company/gobierno-de-la-ciudad-de-buenos-aires/ ", 
                descripcion: "Breve Descripcion del Producto para mostrar al hacer click"},
    {id:5, nombre: "Ágora Public Affairs", 
                img: "./img/Logos/LogoAgora.jfif",
                Phone: "", 
                Mail:"", 
                WebSite:"https://agoraasuntospublicos.com" , 
                linkedIn: "https://ar.linkedin.com/company/agora-public-affairs-&-strategic-communications", 
                descripcion: "Breve Descripcion del Producto para mostrar al hacer click"},
    {id:6, nombre: "Consejo Argentino de RRII", 
                img: "./img/Logos/LogoCari.JPG",
                Phone: "", 
                Mail:"", 
                WebSite:"https://www.cari.org.ar" , 
                linkedIn: "https://ar.linkedin.com/company/consejo-argentino-para-las-relaciones-internacionales-cari-", 
                descUno: LLYCParrUno, descDos: LLYCParrDos, descTres: LLYCParrTres},
    {id:7, nombre: "Willard Grant Agency", 
                img: "./img/Logos/LogoWC.jpg",
                Phone: "", 
                Mail:"",
                WebSite:"https://willardgrant.com" , 
                linkedIn: "https://www.linkedin.com/company/willard-grant-agency/", 
                descripcion: "Breve Descripcion del Producto para mostrar al hacer click"},
    {id:8, nombre: "Embajada de EEUU", 
                img: "./img/Logos/LogoUSA.png",
                Phone: "", 
                Mail:"",
                WebSite:"https://ar.usembassy.gov/es/" ,
                linkedIn: "https://ar.linkedin.com/showcase/embajadaeeuuarg", 
                descripcion: "Breve Descripcion del Producto para mostrar al hacer click"},
    {id:9, nombre: "Embajada de Israel", 
                img: "./img/Logos/LogoIsrael.jfif",
                Phone: "", 
                Mail:"", 
                WebSite:"http://embassies.gov.il/buenos-aires/" , 
                linkedIn: "https://www.linkedin.com/company/embajada-de-israel-en-argentina/about/", 
                descripcion: "Breve Descripcion del Producto para mostrar al hacer click"},
    {id:10, nombre: "Cámara de Comercio de EEUU en Argentina", 
                img: "./img/Logos/LogoAmCham.jpg",
                Phone: "", 
                Mail:"", 
                WebSite:"https://www.amcham.com.ar/" , 
                linkedIn:"https://www.linkedin.com/company/amcham-argentina/", 
                descripcion: "Breve Descripcion del Producto para mostrar al hacer click"},
    {id:11, nombre: "Campus France", 
                img: "./img/Logos/LogoFrance.jpg",
                Phone: "", 
                Mail:"", 
                WebSite:"http://www.campusfrance.org/" , 
                linkedIn: "https://www.linkedin.com/company/campusfrance/", 
                descripcion: "Breve Descripcion del Producto para mostrar al hacer click"},
    {id:12, nombre: "Fundación Libertad y Progreso", 
                img: "./img/Logos/LogoLyP.jpg",
                Phone: "", 
                Mail:"", 
                WebSite:"ttps://www.libertadyprogreso.org/" , 
                linkedIn: "https://www.linkedin.com/in/libertadyprogreso/", 
                descripcion: "Breve Descripcion del Producto para mostrar al hacer click"},
    
    )